# Generated by Django 5.0 on 2024-09-23 02:41

import django_countries.fields
import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', verbose_name='Telefone')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('street', models.CharField(max_length=255, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('objective', models.TextField(verbose_name='Objetivo do Paciente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
