# Generated by Django 5.0 on 2024-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_client_options_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='another_activity',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Outra atividade'),
        ),
        migrations.AddField(
            model_name='client',
            name='coment_memory',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='client',
            name='coment_sleep',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.BooleanField(default=True, verbose_name='Trabalha'),
        ),
        migrations.AddField(
            model_name='client',
            name='memory',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Regular', 'Regular'), ('Péssimo', 'Péssimo')], default='Bom', max_length=10, verbose_name='Memória'),
        ),
        migrations.AddField(
            model_name='client',
            name='sleep',
            field=models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Ruim', 'Ruim')], default='Ótimo', max_length=10, verbose_name='Qualidade do Sono'),
        ),
        migrations.AddField(
            model_name='client',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AddField(
            model_name='client',
            name='study',
            field=models.BooleanField(default=True, verbose_name='Estuda'),
        ),
        migrations.AddField(
            model_name='client',
            name='time_another',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='client',
            name='time_job',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='client',
            name='time_study',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='client',
            name='what_work',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Qual?'),
        ),
        migrations.AddField(
            model_name='client',
            name='work',
            field=models.BooleanField(default=True, verbose_name='Atividade física'),
        ),
    ]
