# Generated by Django 5.0 on 2024-09-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_client_another_activity_client_coment_memory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cirgury',
            field=models.BooleanField(default=False, verbose_name='Cirurgia'),
        ),
        migrations.AddField(
            model_name='client',
            name='cook',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Quem cozinha na sua casa?'),
        ),
        migrations.AddField(
            model_name='client',
            name='family_sick',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doenças existentes na família?'),
        ),
        migrations.AddField(
            model_name='client',
            name='sick',
            field=models.BooleanField(default=False, verbose_name='Doença'),
        ),
        migrations.AddField(
            model_name='client',
            name='smoke',
            field=models.BooleanField(default=True, verbose_name='Fumo'),
        ),
        migrations.AddField(
            model_name='client',
            name='times_smoke',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantidade por dia?'),
        ),
        migrations.AddField(
            model_name='client',
            name='where_eat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Onde você come normalmente?'),
        ),
        migrations.AddField(
            model_name='client',
            name='which_cirgury',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual cirurgia?'),
        ),
        migrations.AddField(
            model_name='client',
            name='which_sick',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual doença?'),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medicamento')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosagem')),
                ('schedule', models.CharField(max_length=50, verbose_name='Horário')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='consulta.client')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
