# Generated by Django 5.0 on 2024-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_alter_medication_options_alter_medication_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='diet',
            field=models.BooleanField(default=False, verbose_name='Hábito de fazer dieta'),
        ),
        migrations.AddField(
            model_name='client',
            name='difficulty',
            field=models.TextField(blank=True, null=True, verbose_name='Quais são suas maiores dificuldades?'),
        ),
        migrations.AddField(
            model_name='client',
            name='drink_when_eat',
            field=models.BooleanField(default=True, verbose_name='Ingere líquidos com as refeições?'),
        ),
        migrations.AddField(
            model_name='client',
            name='flavor',
            field=models.CharField(choices=[('Amargo', 'Amargo'), ('Azedo', 'Azedo'), ('Doce', 'Doce'), ('Salgado', 'Salgado')], default='Salgado', max_length=10, verbose_name='Preferência de sabor'),
        ),
        migrations.AddField(
            model_name='client',
            name='food_behavior',
            field=models.TextField(blank=True, null=True, verbose_name='Como é o seu comportamento em relação à comida?'),
        ),
        migrations.AddField(
            model_name='client',
            name='frequency_rest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frequência que come fora?'),
        ),
        migrations.AddField(
            model_name='client',
            name='hate_eat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Não come de jeito nenhum?'),
        ),
        migrations.AddField(
            model_name='client',
            name='hungry',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Noite', max_length=10, verbose_name='Horário de maior apetite'),
        ),
        migrations.AddField(
            model_name='client',
            name='ih',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ingestão hídrica?'),
        ),
        migrations.AddField(
            model_name='client',
            name='love_eat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='O que ama comer?'),
        ),
        migrations.AddField(
            model_name='client',
            name='mastigate',
            field=models.CharField(choices=[('Rápida', 'Rápida'), ('Normal', 'Normal'), ('Lenta', 'Lenta')], default='Normal', max_length=10, verbose_name='Mastigação'),
        ),
        migrations.AddField(
            model_name='client',
            name='motivation_number',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='10', max_length=2, verbose_name='De 0 a 10, quanto você está comprometido(a) com o nosso tratamento?'),
        ),
        migrations.AddField(
            model_name='client',
            name='nutritionist',
            field=models.TextField(blank=True, null=True, verbose_name='O que você espera de mim como sua nutricionista?'),
        ),
        migrations.AddField(
            model_name='client',
            name='restaurant',
            field=models.BooleanField(default=True, verbose_name='Consumo de fast food ou restaurante?'),
        ),
        migrations.AddField(
            model_name='client',
            name='search',
            field=models.TextField(blank=True, null=True, verbose_name='O que você veio buscar aqui exatamente?'),
        ),
        migrations.AddField(
            model_name='client',
            name='social',
            field=models.TextField(blank=True, null=True, verbose_name='Como é a sua vida social?'),
        ),
        migrations.AddField(
            model_name='client',
            name='stress',
            field=models.TextField(blank=True, null=True, verbose_name='Existe alguma situação de estresse que você esteja passando nesse momento?'),
        ),
        migrations.AddField(
            model_name='client',
            name='tryed_before',
            field=models.BooleanField(default=True, verbose_name='Você já tentou chegar nesse resultado outras vezes?'),
        ),
        migrations.AddField(
            model_name='client',
            name='what_hapened',
            field=models.TextField(blank=True, null=True, verbose_name='O que aconteceu para você chegar no estado atual?'),
        ),
        migrations.AddField(
            model_name='client',
            name='why_get_keep',
            field=models.TextField(blank=True, null=True, verbose_name='por que até hoje não conseguiu chegar e se manter nele?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo do Paciente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='smoke',
            field=models.BooleanField(default=False, verbose_name='Fumo'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='Paciente',
        ),
    ]
