# Generated by Django 5.0 on 2024-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_alter_client_options_client_diet_client_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Irritability',
            field=models.BooleanField(default=False, verbose_name='Irritabilidade'),
        ),
        migrations.AddField(
            model_name='client',
            name='Mastalgia',
            field=models.BooleanField(default=False, verbose_name='Mastalgia'),
        ),
        migrations.AddField(
            model_name='client',
            name='acne',
            field=models.BooleanField(default=False, verbose_name='Acne'),
        ),
        migrations.AddField(
            model_name='client',
            name='anxiety',
            field=models.BooleanField(default=False, verbose_name='Ansiedade'),
        ),
        migrations.AddField(
            model_name='client',
            name='colic',
            field=models.BooleanField(default=False, verbose_name='Cólica'),
        ),
        migrations.AddField(
            model_name='client',
            name='cracked_tongue_middle',
            field=models.BooleanField(default=False, verbose_name='Língua rachada (meio)'),
        ),
        migrations.AddField(
            model_name='client',
            name='cracked_tongue_sides',
            field=models.BooleanField(default=False, verbose_name='Língua rachada (laterais)'),
        ),
        migrations.AddField(
            model_name='client',
            name='depression',
            field=models.BooleanField(default=False, verbose_name='Depressão'),
        ),
        migrations.AddField(
            model_name='client',
            name='dermatitis',
            field=models.BooleanField(default=False, verbose_name='Dermatite/urticária'),
        ),
        migrations.AddField(
            model_name='client',
            name='desire_sweets',
            field=models.BooleanField(default=False, verbose_name='Vontade de comer doce'),
        ),
        migrations.AddField(
            model_name='client',
            name='dry_hair',
            field=models.BooleanField(default=False, verbose_name='Cabelo seco e quebradiço'),
        ),
        migrations.AddField(
            model_name='client',
            name='dry_skin',
            field=models.BooleanField(default=False, verbose_name='Pele seca/descamando'),
        ),
        migrations.AddField(
            model_name='client',
            name='gray_tongue',
            field=models.BooleanField(default=False, verbose_name='Língua acinzentada'),
        ),
        migrations.AddField(
            model_name='client',
            name='hair_loss',
            field=models.BooleanField(default=False, verbose_name='Queda de cabelo'),
        ),
        migrations.AddField(
            model_name='client',
            name='halitosis',
            field=models.BooleanField(default=False, verbose_name='Halitose'),
        ),
        migrations.AddField(
            model_name='client',
            name='inflamed',
            field=models.BooleanField(default=False, verbose_name='Gengiva sangrando/inflamada'),
        ),
        migrations.AddField(
            model_name='client',
            name='irregular_menstrual_cycle',
            field=models.BooleanField(default=False, verbose_name='Ciclo menstrual irregular'),
        ),
        migrations.AddField(
            model_name='client',
            name='labile_mood',
            field=models.BooleanField(default=False, verbose_name='Humor lábil'),
        ),
        migrations.AddField(
            model_name='client',
            name='mouth_ulcer',
            field=models.BooleanField(default=False, verbose_name='Afta'),
        ),
        migrations.AddField(
            model_name='client',
            name='oily_skin',
            field=models.BooleanField(default=False, verbose_name='Pele oleosa'),
        ),
        migrations.AddField(
            model_name='client',
            name='ribbed_nails',
            field=models.BooleanField(default=False, verbose_name='Unhas estriadas'),
        ),
        migrations.AddField(
            model_name='client',
            name='stained_nails',
            field=models.BooleanField(default=False, verbose_name='Unhas com manchas'),
        ),
        migrations.AddField(
            model_name='client',
            name='swelling',
            field=models.BooleanField(default=False, verbose_name='Inchaço'),
        ),
        migrations.AddField(
            model_name='client',
            name='tpm',
            field=models.BooleanField(default=False, verbose_name='TPM'),
        ),
        migrations.AddField(
            model_name='client',
            name='wavy_nails',
            field=models.BooleanField(default=False, verbose_name='Unhas onduladas'),
        ),
        migrations.AddField(
            model_name='client',
            name='weak_nails',
            field=models.BooleanField(default=False, verbose_name='Unhas fracas e quebradiças'),
        ),
        migrations.AddField(
            model_name='client',
            name='whitish_tongue',
            field=models.BooleanField(default=False, verbose_name='Língua esbranquiçada'),
        ),
    ]
