# Generated by Django 5.0 on 2024-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_client_irritability_client_mastalgia_client_acne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Irritability',
            new_name='irritability',
        ),
        migrations.AddField(
            model_name='client',
            name='alcohol',
            field=models.TextField(blank=True, null=True, verbose_name='Consumo de álcool'),
        ),
        migrations.AddField(
            model_name='client',
            name='breakfast',
            field=models.TextField(blank=True, null=True, verbose_name='Desjejum'),
        ),
        migrations.AddField(
            model_name='client',
            name='collation',
            field=models.TextField(blank=True, null=True, verbose_name='Colação'),
        ),
        migrations.AddField(
            model_name='client',
            name='dinner',
            field=models.TextField(blank=True, null=True, verbose_name='Jantar'),
        ),
        migrations.AddField(
            model_name='client',
            name='diuresis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diurese'),
        ),
        migrations.AddField(
            model_name='client',
            name='eat_workout',
            field=models.TextField(blank=True, null=True, verbose_name='Pré e pós treino'),
        ),
        migrations.AddField(
            model_name='client',
            name='favorite_place',
            field=models.TextField(blank=True, null=True, verbose_name='Local favorito para comer'),
        ),
        migrations.AddField(
            model_name='client',
            name='intestine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função intestinal'),
        ),
        migrations.AddField(
            model_name='client',
            name='lunch',
            field=models.TextField(blank=True, null=True, verbose_name='Almoço'),
        ),
        migrations.AddField(
            model_name='client',
            name='nips',
            field=models.TextField(blank=True, null=True, verbose_name='Beliscos'),
        ),
        migrations.AddField(
            model_name='client',
            name='snack',
            field=models.TextField(blank=True, null=True, verbose_name='Lanche da tarde'),
        ),
        migrations.AddField(
            model_name='client',
            name='supper',
            field=models.TextField(blank=True, null=True, verbose_name='Ceia'),
        ),
    ]
