# Generated by Django 5.0 on 2024-09-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_rename_irritability_client_irritability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Mastalgia',
            new_name='mastalgia',
        ),
    ]
