# Generated by Django 5.0 on 2024-09-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_rename_mastalgia_client_mastalgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='schedule',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ácido úrico', 'Ácido úrico'), ('Cálcio', 'Cálcio'), ('Colesterol', 'Colesterol'), ('Creatinina', 'Creatinina'), ('Eosinófilo', 'Eosinófilo'), ('Eritrócito', 'Eritrócito'), ('Ferritina', 'Ferritina'), ('Ferro', 'Ferro'), ('Filt. Glomerular', 'Filt. Glomerular'), ('Glicemia', 'Glicemia'), ('HB1AC', 'HB1AC'), ('HDL', 'HDL'), ('Hematócrito', 'Hematócrito'), ('Hemoglobina', 'Hemoglobina'), ('Insulina', 'Insulina'), ('LDL', 'LDL'), ('Plaquetas', 'Plaquetas'), ('Sódio', 'Sódio'), ('T3', 'T3'), ('T4', 'T4'), ('TGO', 'TGO'), ('TGP', 'TGP'), ('Transferrina', 'Transferrina'), ('Triglicérideos', 'Triglicérideos'), ('TSH', 'TSH'), ('Uréia', 'Uréia'), ('VCM', 'VCM'), ('Vitamina B12', 'Vitamina B12'), ('Vitamina B9', 'Vitamina B9'), ('Vitamina D', 'Vitamina D'), ('Vitamina K', 'Vitamina K'), ('Zinco', 'Zinco')], max_length=100, verbose_name='Exame')),
                ('schedule', models.DateField(verbose_name='Data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='consulta.client')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
    ]
