# Generated by Django 5.0 on 2024-09-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_exam_result_anthropometricevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='conduct',
            field=models.TextField(blank=True, null=True, verbose_name='Conduta'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='abdomen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Abdômen (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Gordura (%)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='body_water_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Água Corporal (%)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='bone_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Massa Óssea (kg)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='bust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Busto (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='calf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='forearm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='hips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quadril (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='metabolic_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade Metabólica (anos)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Massa Muscular (kg)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='non_fat_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Massa Não Adiposa (kg)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='proximal_thigh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa Proximal (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='relaxed_arm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço Relaxado (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='visceral_fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gordura Visceral (%)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
