# Generated by Django 5.0 on 2024-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_anthropometricevaluation_conduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_abdominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Abdominal (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_biceps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Bíceps (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_coxa_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Coxa Média (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_crista_iliaca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Crista Ilíaca (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_panturrilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Panturrilha (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_subescapular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Subescapular (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_supraespinhal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Supraespinhal (cm)'),
        ),
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='dc_triceps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Tríceps (cm)'),
        ),
        migrations.AddField(
            model_name='client',
            name='desired_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso desejado (kg)'),
        ),
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
    ]
