# Generated by Django 5.0 on 2024-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0013_anthropometricevaluation_dc_abdominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthropometricevaluation',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_abdominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Abdominal (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_biceps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Bíceps (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_coxa_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Coxa Média (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_crista_iliaca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Crista Ilíaca (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_panturrilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Panturrilha (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_subescapular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Subescapular (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_supraespinhal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Supraespinhal (mm)'),
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='dc_triceps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DC Tríceps (mm)'),
        ),
    ]
