# Generated by Django 5.0 on 2024-10-12 22:57

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_anthropometricevaluation_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_another',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='client',
            name='what_work',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual?'),
        ),
    ]
