# Generated by Django 5.0 on 2024-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0015_alter_client_cpf_alter_client_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='anthropometricevaluation',
            name='conduct',
            field=models.TextField(blank=True, null=True, verbose_name='Evolução'),
        ),
    ]
